### ISSUE TITLE
Scripts don't honor preview build channels

### ISSUE THREAD

**Issue by timheuer** [dotnet/install-scripts#180]
This should work:

`dotnet-install.ps1 -Channel 6.0`

And give me back the latest preview from the 6.0 channel (valid channel in releases.json)

**Comment by bozturkMSFT** [comment]
Thank you @timheuer. I will check this to see what's wrong.

**Comment by bozturkMSFT** [comment]
@timheuer As part of the updates to the release pipeline here https://github.com/dotnet/arcade/issues/6418, there are some changes to the URLs of the installers. We have updated the install scripts to accommodate these changes, but we haven't published the updated version yet since the work on the pipeline side is not yet complete.

The following items need to be closed before we can release:
 - https://github.com/dotnet/arcade/issues/7239
 - https://github.com/dotnet/arcade/issues/7240 
 - https://github.com/dotnet/arcade/issues/7295

After the release, the scripts can be used to download .NET 6.0.

**Comment by timheuer** [comment]
Thanks @bozturkMSFT!  When this work is finalized, any future previews should work then correct? So after 6.0 is released and we are on 7.0 previews, it should 'just work' to find the 7.0 preview bits if they exist?

**Comment by bozturkMSFT** [comment]
That is correct. These changes will hopefully minimize the manual work needed to make a new version available to the scripts by automating the steps for us.

**Comment by bozturkMSFT** [comment]
This is temporarily fixed now as we have the required latest.version file in the blob storage. The file will need to be updated manually until the work items above are completed. I will close this for now. Please reopen if needed.

**Comment by timheuer** [comment]
Thanks...the actions/setup-dotnet is still not working but feels like a problem in that script now...engaging with that team.

**Comment by bozturkMSFT** [comment]
The scenarios I have tested seemed to be working, but it is also possible that I missed something. In any case, let me know if there is anything I can help with.

**Comment by timheuer** [comment]
Here is an example: https://github.com/timheuer/test-console/blob/master/.github/workflows/build.yml#L23-L26
