### ISSUE TITLE
script webpage is down

### ISSUE THREAD

**Issue by JanProvaznik** [dotnet/install-scripts#487]
https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1

HTTP Error 500.30 - ASP.NET Core app failed to start
Common solutions to this issue:
The app failed to start
The app started but then stopped
The app started but threw an exception during startup
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect

**Comment by YuliiaKovalova** [comment]
@baronfel , @mairaw  could you check it out with the high priority?

**Comment by baronfel** [comment]
An ICM has been created for this internally

**Comment by slang25** [comment]
Thanks @baronfel, this is blocking all of our .NET builds, we have workarounds but the impact is wide reaching

**Comment by YuliiaKovalova** [comment]
It's also has been tracked here: https://github.com/dotnet/runtime/issues/104230

**Comment by slang25** [comment]
For the sake of others reading this, a workaround (courtesy of @martincostello) is to use the following urls while the dotnet subdomain is down:
* https://raw.githubusercontent.com/dotnet/install-scripts/main/src/dotnet-install.sh
* https://raw.githubusercontent.com/dotnet/install-scripts/main/src/dotnet-install.ps1

**Comment by baronfel** [comment]
Similar reports on other repos for tracking/correlation:

* https://github.com/dotnet/core/issues/9376
* https://github.com/dotnet/sdk/issues/41875
* https://github.com/dotnet/runtime/issues/104230

**Comment by mairaw** [comment]
Apologies for the inconvenience. We are currently working on this and I'll update all issues once it's resolved.

**Comment by mairaw** [comment]
Issue is now resolved. Let us know if you're still having trouble.

**Comment by lucaspimentel** [comment]
Just a heads up that links like these still fail:
https://dotnet.microsoft.com/get-dotnet/dotnet-core?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.22.04-x64&os=ubuntu.22.0


This is generated when running a .NET app without the correct runtime installed:
```
> ./mydotnet6app

You must install or update .NET to run this application.

App: /home/lucas/source/datadog/dd-trace-dotnet/tracer/test/test-applications/integrations/Samples.Console/bin/Debug/net6.0/publish/Samples.Console
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/lib/dotnet

The following frameworks were found:
  7.0.19 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
  8.0.5 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.22.04-x64&os=ubuntu.22.04
```

**Comment by mairaw** [comment]
Yes, we were missing one more service update.
